[package]
name = "uniparser"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
image = "0.24.2"
plotters = "0.3.1"
plotters-cairo = "0.3.1"
